name: CI

on:
  # Run the CI process on any push to the main branch
  push:
    branches:
    - main
  
  # Run the CI process on an PR that wants to merge into the main branch.
  # Optionally, under GitHub Branches settings, set 'Require status checks to pass
  # before merging' to block merges until CI process succeeds.
  pull_request:
    branches:
    - main

jobs:

  # Linting process with Selene
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Foreman & all tools listed in foreman.toml
    - uses: Roblox/setup-foreman@v1
      name: Install Foreman
      with:
          version: "^1.0.0"
          token: ${{ SECRETS.GITHUB_TOKEN }}

    # Run selene against the src directory
    - name: Lint
      run: |
        selene ./src

  # Run unit tests using TestEZ (TestEZ is a dependency listed in wally.toml)
  unit-tests:
    name: Unit Tests
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Roblox Studio (requires a ROBLOSECURITY secret in the GitHub repository)
      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Install Foreman & all tools listed in foreman.toml
      - name: Install Foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Install dependencies listed in wally.toml
      - name: Wally Install
        run: wally install

      # Create a test.rbxl file based on the Rojo configuration
      - name: Build test place
        run: rojo build default.project.json -o test.rbxl

      # Run the ci.lua file as a plugin within Roblox Studio, and write printed results to test-out.txt
      - name: Run tests
        run: run-in-roblox --place test.rbxl --script ci.lua > test-out.txt
        continue-on-error: true
        timeout-minutes: 5
        
      # Check that TestEZ succeeded by making sure it printed out that nothing failed
      - name: Check test status
        shell: bash
        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
